[package]
name = "rust-coverage-example"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]

[[bin]]
name = "calculator"
path = "src/main.rs"

[lib]
name = "calculator"
path = "src/lib.rs"
